apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-206119/pipeline:91aeecb797a08b69c64a95fa251155b1222fa984
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
