apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-206119/pipeline:64027f330b3efe7d593a91524e9858b0e4e9cad4
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
